# Generated by Django 5.0 on 2024-01-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_payment',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
    ]
